#!/bin/sh
if test $(id -u) != 0; then
        echo Error: You must be root to run this script!
        exit 1
fi
tzsetup
# see why Op not permitted. 
#NTPSERVERS="pool.ntp.org"
#ntpdate -u -b $NTPSERVERS 

